/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "search" | "Sidebar1" | "Sidebar10" | "Sidebar11" | "Sidebar12" | "Sidebar13" | "Sidebar14" | "Sidebar15" | "Sidebar16" | "Sidebar17" | "Sidebar18" | "Sidebar19" | "Sidebar2" | "Sidebar20" | "Sidebar21" | "Sidebar22" | "Sidebar23" | "Sidebar24" | "Sidebar25" | "Sidebar3" | "Sidebar4" | "Sidebar5" | "Sidebar6" | "Sidebar7" | "Sidebar8" | "Sidebar9">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "search" | "Sidebar1" | "Sidebar10" | "Sidebar11" | "Sidebar12" | "Sidebar13" | "Sidebar14" | "Sidebar15" | "Sidebar16" | "Sidebar17" | "Sidebar18" | "Sidebar19" | "Sidebar2" | "Sidebar20" | "Sidebar21" | "Sidebar22" | "Sidebar23" | "Sidebar24" | "Sidebar25" | "Sidebar3" | "Sidebar4" | "Sidebar5" | "Sidebar6" | "Sidebar7" | "Sidebar8" | "Sidebar9">;
          default: string;
          required: true;
      };
  }>>, {
      name: "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "search" | "Sidebar1" | "Sidebar10" | "Sidebar11" | "Sidebar12" | "Sidebar13" | "Sidebar14" | "Sidebar15" | "Sidebar16" | "Sidebar17" | "Sidebar18" | "Sidebar19" | "Sidebar2" | "Sidebar20" | "Sidebar21" | "Sidebar22" | "Sidebar23" | "Sidebar24" | "Sidebar25" | "Sidebar3" | "Sidebar4" | "Sidebar5" | "Sidebar6" | "Sidebar7" | "Sidebar8" | "Sidebar9";
  }>;
  export const svgNames: ["dashboard", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "search", "Sidebar1", "Sidebar10", "Sidebar11", "Sidebar12", "Sidebar13", "Sidebar14", "Sidebar15", "Sidebar16", "Sidebar17", "Sidebar18", "Sidebar19", "Sidebar2", "Sidebar20", "Sidebar21", "Sidebar22", "Sidebar23", "Sidebar24", "Sidebar25", "Sidebar3", "Sidebar4", "Sidebar5", "Sidebar6", "Sidebar7", "Sidebar8", "Sidebar9"];
  export type SvgName = "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "search" | "Sidebar1" | "Sidebar10" | "Sidebar11" | "Sidebar12" | "Sidebar13" | "Sidebar14" | "Sidebar15" | "Sidebar16" | "Sidebar17" | "Sidebar18" | "Sidebar19" | "Sidebar2" | "Sidebar20" | "Sidebar21" | "Sidebar22" | "Sidebar23" | "Sidebar24" | "Sidebar25" | "Sidebar3" | "Sidebar4" | "Sidebar5" | "Sidebar6" | "Sidebar7" | "Sidebar8" | "Sidebar9";
  export default SvgIcon;
}
